class State < ActiveHash::Base
  extend ActiveHash::Associations::ActiveRecordExtensions
 self.data = [
 { id: 0, name: '___'},
 { id: 1, name: '千代田区', direction_id:"1"},
 { id: 2, name: '中央区', direction_id:"1"},
 { id: 3, name: '港区', direction_id:"1"},
 { id: 4, name: '新宿区', direction_id:"4"},
 { id: 5, name: '文京区', direction_id:"1"},
 { id: 6, name: '台東区', direction_id:"1"},
 { id: 7, name: '墨田区', direction_id:"7"},
 { id: 8, name: '江東区', direction_id:"7"},
 { id: 9, name: '品川区', direction_id:"2"},
 { id: 10, name: '目黒区', direction_id:"3"},
 { id: 11, name: '大田区', direction_id:"2"},
 { id: 12, name: '世田谷区', direction_id:"3"},
 { id: 13, name: '渋谷区', direction_id:"3"},
 { id: 14, name: '中野区', direction_id:"4"},
 { id: 15, name: '杉並区', direction_id:"4"},
 { id: 16, name: '豊島区', direction_id:"5"},
 { id: 17, name: '北区', direction_id:"5"},
 { id: 18, name: '荒川区', direction_id:"6"},
 { id: 19, name: '板橋区', direction_id:"10"},
 { id: 20, name: '練馬区', direction_id:"10"},
 { id: 21, name: '足立区', direction_id:"6"},
 { id: 22, name: '葛飾区', direction_id:"6"},
 { id: 23, name: '江戸川区', direction_id:"7"},
 { id: 24, name: '八王子市', direction_id:"9"},
 { id: 25, name: '立川市', direction_id:"8"},
 { id: 26, name: '武蔵野市', direction_id:"8"},
 { id: 27, name: '三鷹市', direction_id:"8"},
 { id: 28, name: '青梅市', direction_id:"9"},
 { id: 29, name: '府中市', direction_id:"8"},
 { id: 30, name: '昭島市', direction_id:"8"},
 { id: 31, name: '調布市', direction_id:"8"},
 { id: 32, name: '町田市', direction_id:"9"},
 { id: 33, name: '小金井市', direction_id:"8"},
 { id: 34, name: '小平市', direction_id:"8"},
 { id: 35, name: '日野市', direction_id:"9"},
 { id: 36, name: '東村山市', direction_id:"8"},
 { id: 37, name: '国分寺市', direction_id:"8"},
 { id: 38, name: '国立市', direction_id:"8"},
 { id: 39, name: '福生市', direction_id:"9"},
 { id: 40, name: '狛江市', direction_id:"8"},
 { id: 41, name: '東大和市', direction_id:"8"},
 { id: 42, name: '清瀬市', direction_id:"8"},
 { id: 43, name: '東久留米市', direction_id:"8"},
 { id: 44, name: '武蔵村山市', direction_id:"8"},
 { id: 45, name: '多摩市', direction_id:"9"},
 { id: 46, name: '稲城市', direction_id:"1"},
 { id: 47, name: '羽村市', direction_id:"9"},
 { id: 48, name: 'あきる野市', direction_id:"9"},
 { id: 49, name: '西東京市', direction_id:"8"},
 { id: 50, name: '日の出村', direction_id:"9"},
 { id: 51, name: '檜原村', direction_id:"9"},
 { id: 52, name: '奥多摩町', direction_id:"9"},
 ]



include ActiveHash::Associations
  has_many :posts

end